### ISSUE TITLE
onboardingService.authenticate(); hangs if no network connection is present

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_libraries#271] opened 2022-12-19 16:51 UTC
### Describe the bug

When using

    var onboard = await onboardingService.authenticate();
    
    My expected result was true if onboarded and false if the onboarding fails. But if there is for example no Internet connection then this call hangs and does not return or throw an exception. If the Internet comes back online then the onboarding seems to continue, but this await never returns true.

### Steps to reproduce

1. First I set up a VM that I can console into (so dropping the internet does not cut me off!)
2. Then switch off the connection to the Internet 
3. And then run att_talk or  similar that uses the     var onboard = await onboardingService.authenticate(); call
4. Watch the logs and see the call is hung
5. Bring back the Internet connection and see a partial recovery but the     var onboard = await onboardingService.authenticate(); never returns the future

### Expected behavior

Expected that a false would return if the onboarding fails for some reason (e.g. secondary lookup fails or network check fails). Or perhaps an exception to be thrown ? 

Either would be fine but a hang is problematic

### Screenshots

https://user-images.githubusercontent.com/6131216/208477780-db073b0f-91cf-4fb6-bce0-bb65bb7c1a73.mp4

### Smartphones

-Linux Dart
2.17.6

### Were you using an atApplication when the bug was found?

at_talk  - branch nosync

**Comment by gkc** [comment] 2023-01-04 14:37
@cconstab Please try with dependency override for at_lookup using branch gkc-debugging-branch
```yaml
dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: gkc-debugging-branch
```

Relevant changes:
1) SecureSocket create should time out after 10 seconds
2) CRAM authenticate should time out if 4 seconds (transientWaitTime) passes without receiving some (even partial) response, and after 10 seconds (maxWaitTime) if full response has not been received
3) PKAM authenticate should time out if 4 seconds (transientWaitTime) passes without receiving some (even partial) response, and after 10 seconds (maxWaitTime) if full response has not been received

For reference, this is what the at_lookup packages on [pub.dev](http://pub.dev/) do i.e. what you are currently using
1) We suggest no timeout when creating SecureSocket and I think even when the network comes back it may just hang for "system default" aka operating system kernel default timeout (I believe usually 3 minutes) and may well hang indefinitely in some situations
2) and 3) CRAM and PKAM requests currently have transientWaitTime of 10 seconds and maxWaitTime of 90 seconds

**Comment by cconstab** [comment] 2023-01-05 01:27
https://user-images.githubusercontent.com/6131216/210680692-1713707d-e327-485d-907c-6785646c4c25.mp4

Not seeing the connection timeout as yet... Video above shows what i see..

Setting up a VM and being able to switch off the eth0/uplink is how I am testing

**Comment by gkc** [comment] 2023-01-05 10:42
@srieteja noted that the root lookup (in CacheableSecondaryAddressFinder class) **also** didn't have a timeout when calling SecureSocket.connect ... and since the root lookup happens first, that's where the hang is almost certainly occurring.

Srie & I just paired for a while and have pushed another change to the gkc-debugging-branch branch ... please `dart pub upgrade` and try again ...

**Comment by cconstab** [comment] 2023-01-05 19:55
Still hanging at the same place -

**Comment by gkc** [comment] 2023-01-05 20:45
Can you run with FINEST log level please Colin and post the logs?

**Comment by srieteja** [comment] 2023-01-06 14:58
I tested the latest changes in gkc-debugging-branch and I was able too see the exception being thrown when I was trying to authenticate with the network being unavailable. In a different case when I turned the network off mid-process(when I call authenticate() and then manually turn network off just before a connection was created) the exception was thrown only sometimes(behaviour was not consistent). In the second case the socket connection attempt was also not being terminated after the timeout duration. Will further look into this.

**Comment by cconstab** [comment] 2023-01-06 17:27
More logging set up with FINER logs

https://user-images.githubusercontent.com/6131216/211065136-bfd7c57f-4fd5-4b52-9cd0-85a96e2604f6.mp4

**Comment by cconstab** [comment] 2023-01-06 17:30
Note if you want to use the same code as I am using to test then use this branch of at_talk

https://github.com/atsign-foundation/at_talk/tree/nosync

**Comment by gkc** [comment] 2023-01-07 14:42
@cconstab I can't easily replicate your network setup so it's not really possible for me to test in the same way. I've slightly modified the logging around SecureSocket.connect in the _findSecondary method in cacheable_secondary_address_finder.dart. Previously
```dart
      _logger.finer('Connecting to root at $_rootDomain:$_rootPort to look up $atsign');
      // ignore: omit_local_variable_types
      socket = await SecureSocket.connect(_rootDomain, _rootPort,
        timeout: Duration(seconds:10));
```

... now changed to

```dart
      var connectTimeout = Duration(seconds:10);
      try {
        _logger.finer('Connecting to root at $_rootDomain:$_rootPort to look up $atsign with timeout $connectTimeout');
        socket = await SecureSocket.connect(_rootDomain, _rootPort, timeout: connectTimeout);
        _logger.finer('Got SecureSocket connection $socket to $_rootDomain:$_rootPort');
      } catch (e, st) {
        _logger.info("Failed to connect with exception $e and stack trace $st");
        rethrow;
      }
```
It certainly _looks_ like SecureSocket.connect's timeout isn't being respected in the particular network state you're testing, but these log messages should let us know for sure

Please can you try one last time just to confirm?

After that, we'll apply the same patch which should prevent this problem from occurring except in extremely rare conditions which is to check network availability before attempting to connect (using https://pub.dev/packages/internet_connection_checker like at_client does in similar situations)

**Comment by gkc** [comment] 2023-01-07 14:58
PS I've just made another change from 
```dart
        socket = await SecureSocket.connect(_rootDomain, _rootPort, timeout: connectTimeout);
```
to
```dart
        // If the SecureSocket.connect times out after `connectTimeout`, it will (allegedly) throw a SocketException
        // If the Future.timeout() after `connectTimeout * 1.5` causes the timeout, it will throw a TimeoutException
        socket = await SecureSocket.connect(_rootDomain, _rootPort, timeout: connectTimeout).timeout(connectTimeout * 1.5);
```

**Comment by cconstab** [comment] 2023-01-07 23:27
So new error message straight away in name resolution.. Hope that gives some clues

https://user-images.githubusercontent.com/6131216/211173920-8c661e93-a511-4f98-bacc-77025ce5d4e2.mp4

**Comment by gkc** [comment] 2023-01-07 23:35
Didn't make any change which could have affected  in that way. Different network conditions to your previous test? Do you know if anything was different?
[UPDATE: It was not]

**Comment by gkc** [comment] 2023-01-07 23:45
Looking at your code in at_talk, you have a loop checking the Boolean response from onboarding.authenticate 

Somehow, it looks like the authenticate is perhaps returning true? Otherwise I'd surely expect to see your loop retrying the call to authenticate pretty much immediately. 

Can you log (in at_talk) what the return value from authenticate is, please?

[UPDATE: It was not]

**Comment by gkc** [comment] 2023-01-07 23:59
PS at this point, looks like the exception handling in this part of the codebase is borked somewhere. I'll check through all of the exception handling in the morning.

**Comment by gkc** [comment] 2023-01-08 00:37
I couldn't wait until the morning. Debugging the exception handling now. Problem reproduced, now diagnosing and then hopefully will fix.

**Comment by gkc** [comment] 2023-01-08 00:43
It's our old friend, an uncaught exception

**Comment by gkc** [comment] 2023-01-08 01:37
@cconstab Got to the bottom of the problem. Have pushed a fix to at_talk's exception handling in your nosync branch, and another cosmetic change to an exception message in at_lookup. Please update your nosync branch from github, dart pub upgrade, and try again

**Comment by cconstab** [comment] 2023-01-08 05:42
One exception to catch but its working yay!!! THANKS GARY!


https://user-images.githubusercontent.com/6131216/211182278-d34ef289-9f73-485e-931e-912fbd0b5b9e.mp4

**Comment by gkc** [comment] 2023-01-09 01:15
Between @cconstab @srieteja and @gkc I reckon this easily consumed 8SP in PR52. I estimate we need 2 or 3 SP in PR53 to get any useful changes merged to trunk and published.

**Closed as completed** 2023-01-23 15:58 UTC
Labels: bug, 3 SP, PR53
